GET http://218.28.15.90:88/SPR/RewController/findEquByStationName.do?vcStationName=%E9%B2%98%E9%97%A8
Accept: application/json

### 接口6：同步车站设备和器材对应关系
POST http://changsha.zhongchengkeshi.com/api/HH/entireInstanceLogsByEIID
Content-Type: application/json

{
    "vcCodes": "Q010501B04900003034,"
}

### 接口5：根据设备唯一编号获取设备日志
GET http://218.28.15.90:88/SPR/RewController/findQcfxByStationName.do?vcStationName=鲘门
Accept: application/json

### 获取某车站的故障信息
POST http://xxx/api/HH/breakdownExplain
Content-Type: application/json

{
    "vcCodes": [
        "Q020701B04900000748",
        "Q020701B04900000747"
    ],
    "stationName": "常德",
    "crossroadNumber": "道岔号",
    "vcGzxx": "故障描述……",
    "dtGzTime": "2020-10-27 18:17:21",
    "submitterName": "张三"
}

### 接口4：上报现场故障描述
GET http://maintain.test:8888/api/HH/recodesByProcessSN/B04920201106170106038891
Content-Type: application/x-www-form-urlencoded

### 接口3：根据检修过程获取具体检测记录
POST http://maintain.test:8888/api/HH/

POST http://maintain.test:8888/api/HH/fixWorkflowsByEIID
Content-Type: application/json

{
    "vcCodes": "Q010501B04900003034,"
}

### 接口2：根据设备唯一编号获取检修记录
GET http://maintain.test:8888/api/HH/entireInstancesByStationName?station_name=鲘门
Content-Type: application/json
Cache-Control: no-cache

### 接口1：根据车站获取设备列表
GET http://maintain.test:8888/api/HH/entireInstance/Q010102B05200009368
Content-Type: application/json
Cache-Control: no-cache



