GET http://maintain.yujizhou.test:8888/api/basic/category/init
Accept: application/json

### 从数据中台备份到本地
PUT http://maintain.yujizhou.test:8888/api/basic/category/S99
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

name=测试2

### 种类 编辑
POST http://maintain.yujizhou.test:8888/api/basic/category
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

unique_code=S99
&name=测试1

### 种类 新建
GET http://maintain.yujizhou.test:8888/api/basic/category/S99
Accept: application/application/x.fix_workshop.v1+json

### 种类 详情
POST http://spas.zhongchengkeshi.com/transmit
Accept: application/json
# GET http://changsha.zhongchengkeshi.com/api/basic/category?page=1
# Accept: application/application/x.fix_workshop.v1+json

{
    "url":"http://changsha.zhongchengkeshi.com/api/pdaBaseInfo",
    "headers":{
        "account":"admin",
        "password":"123123"
    },
    "method":"GET",
    "params":{
        "page":1
    }
}

### 种类 列表
