DELETE http://maintain.yujizhou.test:8888/api/basic/partModel/S9901N01
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

### 部件类型 删除
PUT http://maintain.yujizhou.test:8888/api/basic/partModel/S9901N01
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

name=测试bb

### 部件类型 编辑
POST http://maintain.yujizhou.test:8888/api/basic/partModel
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

unique_code=S9901N01
&name=测试aa
&category_unique_code=S99
&entire_model_unique_code=S9901

### 部件类型 新建
GET http://maintain.yujizhou.test:8888/api/basic/partModel/S9901N01
Accept: application/application/x.fix_workshop.v1+json

### 部件类型 详情
GET http://maintain.yujizhou.test:8888/api/basic/partModel?page=1
Accept: application/application/x.fix_workshop.v1+json

### 部件类型 列表
