PUT http://maintain.yujizhou.test:8888/api/basic/subModel/S9901
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

name=测试bb

### 子类 编辑
POST http://maintain.yujizhou.test:8888/api/basic/subModel
Content-Type: application/x-www-form-urlencoded
Accept: application/application/x.fix_workshop.v1+json

unique_code=S9901
&name=测试aa
&category_unique_code=S99

### 子类 新建
GET http://maintain.yujizhou.test:8888/api/basic/subModel/S9901
Accept: application/application/x.fix_workshop.v1+json

### 子类 详情
GET http://maintain.yujizhou.test:8888/api/basic/subModel?page=1
Accept: application/application/x.fix_workshop.v1+json

### 子类 列表
