GET http://fix-workshop.test:8888/monitor/cycleFixStatistics/B048D02
Accept: application/json

### 周期修计划统计（次月、段）
GET http://maintain.test:8888/api/pda/entireInstanceByIdentityCode/Q010901B04100000156
Accept: application/json

### 设备详情
GET http://maintain.test:8888/api/monitor/entireInstance?state_name=上道
# GET http://test.hefei.zhongchengkeshi.com/api/monitor/entireInstance?state_name=上道
Accept: application/json

### 监控大屏 设备列表
#GET http://maintain.test:8888/api/monitor/maintain
GET http://test.hefei.zhongchengkeshi.com/api/monitor/maintain
Accept: application/json

### 监控大屏 台长统计（右下）
GET http://maintain.test:8888/api/monitor/scraped
Accept: application/json

### 监控大屏 超期统计（右中）
GET http://maintain.test:8888/api/monitor/breakdown
Accept: application/json

### 监控大屏 故障统计（右上）
#GET http://maintain.test:8888/api/monitor/installing
GET http://test.hefei.zhongchengkeshi.com/api/monitor/installing
Accept: application/json

### 监控大屏 备品统计（左下）
GET http://maintain.test:8888/api/monitor/property
Accept: application/json

### 监控大屏 资产统计（左中）
GET http://maintain.test:8888/api/monitor/status
Accept: application/json

### 监控大屏 状态统计（左上）
GET http://maintain.test:8888/api/monitor/basicInfo
#GET http://test.hefei.zhongchengkeshi.com/api/monitor/basicInfo
Accept: application/json

### 监控大屏 基础信息
