POST http://127.0.0.1:8000/api/wechatMiniApp/tmpMaterialCollection
Content-Type: application/json

{
    "open_id": "onVVO5BwGZrmbB7pLYciHS75rzP8",
    "category_name": "行指系统",
    "entire_model_name": "工控机",
    "sub_model_name": "REXTRON KVM FXDA-MO40",
    "equipment_category_name": "",
    "equipment_entire_model_name": "",
    "equipment_sub_model_name": "",
    "ex_factory_at": "2020-01-01 12:01:11",
    "factory_number": "123456",
    "service_life": "",
    "cycle_fix_at": "2020-05-01 12:01:11",
    "cycle_fix_year": 15,
    "last_installed_at": "2020-02-01 12:01:11",
    "factory_name": "华为",
    "workshop_name": "常德信号车间",
    "station_name": "常德",
    "version_number": "",
    "state_unique_code": "INSTALLED",
    "serial_number": "123456",
    "last_fixed_at": "2020-05-01",
    "next_fixing_at": "2020-05-01",
    "scraping_at":"2020-05-01"
}

### 临时-数据采集-添加


PUT http://127.0.0.1:8000/api/wechatMiniApp/tmpMaterialCollection/{id}
Content-Type: application/json

{
    "open_id": "onVVO5BwGZrmbB7pLYciHS75rzP8",
    "category_name": "行指系统",
    "entire_model_name": "工控机",
    "sub_model_name": "REXTRON KVM FXDA-MO40",
    "equipment_category_name": "",
    "equipment_entire_model_name": "",
    "equipment_sub_model_name": "",
    "ex_factory_at": "2020-01-01 12:01:11",
    "factory_number": "123456",
    "service_life": "",
    "cycle_fix_at": "2020-05-01 12:01:11",
    "cycle_fix_year": 15,
    "last_installed_at": "2020-02-01 12:01:11",
    "factory_name": "华为",
    "workshop_name": "常德信号车间",
    "station_name": "常德",
    "version_number": "",
    "state_unique_code": "INSTALLED",
    "serial_number": "123456",
    "last_fixed_at": "2020-05-01",
    "next_fixing_at": "2020-05-01",
    "scraping_at":"2020-05-01"
}

### 临时-数据采集-编辑  id 临时表ID
DELETE http://127.0.0.1:8000/api/wechatMiniApp/tmpMaterialCollection/{id}

### 临时-数据采集-删除 id 临时表ID
POST http://127.0.0.1:8000/api/wechatMiniApp/collectionOrder
Content-Type: application/json

{
    "open_id": "onVVO5BwGZrmbB7pLYciHS75rzP8"
}

### 数据采集-添加
GET http://127.0.0.1:8000/api/wechatMiniApp/collectionOrder/download
Content-Type: application/json

{
    "unique_code": "1611905984_1"
}

### 数据采集-下载
GET http://127.0.0.1:8000/api/wechatMiniApp/collectionOrder/location?open_id=onVVO5BwGZrmbB7pLYciHS75rzP8
Accept: application/json

### 数据采集-定位-列表
GET http://127.0.0.1:8000/api/wechatMiniApp/positionWithInstallTier?install_tier_unique_code=12B049G00090010101
Accept: application/json

### 根据上道位编码获取层编码
POST http://127.0.0.1:8000/api/wechatMiniApp/collectionOrder/station
#POST http://test.huaihua.zhongchengkeshi.com/api/wechatMiniApp/collectionOrder/station
Content-Type: application/json

{
    "open_id": "ohHTR4vePrfQsbZ17s4F1hoLJU-o",
    "station_unique_name": "中继11站",
    "serial_number": "12203000002"
}

### 数据采集-定位(车站)-添加
POST http://127.0.0.1:8000/api/wechatMiniApp/collectionOrder/location
Content-Type: application/json

{
    "open_id": "onVVO5BwGZrmbB7pLYciHS75rzP8",
    "entire_instance_identity_code": "Q020201B04900000001",
    "install_location_unique_code": "12B049G0009001010101"
}

### 数据采集-定位-添加
GET http://127.0.0.1:8000/api/wechatMiniApp/jsApiSignature?url=http://127.0.0.1:8000/pda
Accept: application/json

### 获取js_api_signature
GET http://127.0.0.1:8000/api/wechatMiniApp/jsApiTicket
Accept: application/json

### 获取js_api_ticket
GET http://127.0.0.1:8000/api/wechatMiniApp/accessToken
Accept: application/json

### 获取access_key
POST http://test.hefei.zhongchengkeshi.com/api/wechatMiniApp/subModel
Content-Type: application/json

{
    "type": "Q",
    "category_unique_code": "Q16",
    "category_name": "测试种",
    "entire_model_unique_code": "Q1601",
    "entire_model_name": "测试类",
    "sub_model_name": "测试型2",
    "fix_cycle_value": 5
}

### 添加种类型
GET http://127.0.0.1:8000/api/wechatMiniApp/test
Accept: application/json

### 测试
GET http://127.0.0.1:8000/api/wechatMiniApp/factories
Accept: application/json

### 获取供应商列表
GET http://127.0.0.1:8000/api/wechatMiniApp/downloadCollectDeviceOrder/6A653F67FE74B4D1923BD51691AE3BBF
Accept: application/json

### 下载基础信息采集单Excel
POST http://127.0.0.1:8000/api/wechatMiniApp/collectDeviceOrder
Content-Type: application/json

{
    "wechat_open_id": "AAA"
}

### 生成基础信息采集单
POST http://127.0.0.1:8000/api/wechatMiniApp/collectDeviceOrderEntireInstance
Content-Type: application/json

{
    "entire_instance_serial_number": "1231",
    "status": "INSTALLED",
    "factory_device_code": "",
    "factory_name": "中国铁道科学研究院",
    "model_unique_code": "Q060101",
    "made_at": "2021-05-25",
    "installed_at": "",
    "cycle_fix_value": "3",
    "life_year": "15",
    "maintain_station_name": "新化南",
    "maintain_location_code": "",
    "wechat_open_id": "ohHTR4ioY0HUMMgxizAHNCTsprWk"
}

### 基础信息采集
GET http://127.0.0.1:8000/api/wechatMiniApp/stationLocationsByWechatOpenId?wechat_open_id=AAA&ordering=id desc
Accept: application/json

### 根据微信openid获取车站补登记录信息
POST http://127.0.0.1:8000/api/wechatMiniApp/stationLocation
Content-Type: application/json

{
    "lon": "111",
    "lat": "222",
    "line_name": "线别名称",
    "connection_name": "联系人",
    "connection_phone": "联系电话",
    "connection_address": "门牌号",
    "maintain_station_name": "常德",
    "wechat_open_id": "AAA"
}

### 车站信息补登
GET http://127.0.0.1:8000/api/wechatMiniApp/wechatOpenIdByJsCode?js_code=021ZqC000BIjYK1X15300jcPoC2ZqC0j
#GET http://127.0.0.1:8000/api/wechatMiniApp/wechatOpenIdByJsCode?js_code=021ZqC000BIjYK1X15300jcPoC2ZqC0j
Accept: application/json

### 微信小程序登陆
#POST https://transmit.zhongchengkeshi.com/api/wechatMiniApp?target=https://hefei.zhongchengkeshi.com/api/wechatMiniApp/registerStationInstallUser
#POST http://transmit-127.0.0.1:8000/api/wechatMiniApp?target=http://127.0.0.1:8000/api/wechatMiniApp/registerStationInstallUser
POST http://127.0.0.1:8000/api/wechatMiniApp/registerStationInstallUser
Content-Type: application/json

{
    "wechat_open_id": "AAA",
    "nickname": "余济舟"
}

### 注册员工
GET https://hefei.zhongchengkeshi.com/api/wechatMiniApp/checkStationInstallUser?wechat_open_id=op-tN5Ktc4vRho0ZZRHFAj93E0jE
GET http://127.0.0.1:8000/api/wechatMiniApp/checkStationInstallUser?wechat_open_id=AAA
Accept: application/json

### 检查员工是否注册
GET http://127.0.0.1:8000/api/wechatMiniApp/subModelsByName?name=JW
Accept: application/json

### 获取根据名称获取种类型
GET http://127.0.0.1:8000/api/wechatMiniApp/subModels
#GET http://changsha.zhongchengkeshi.com/api/wechatMiniApp/subModels
Accept: application/json

### 获取种类型列表
GET http://127.0.0.1:8000/api/wechatMiniApp/stationsByName?name=长沙
Accept: application/json

### 通过名称获取车站
#GET http://127.0.0.1:8000/api/wechatMiniApp/sceneWorkshopsByParagraphUniqueCode/B049
GET http://changsha.zhongchengkeshi.com/api/wechatMiniApp/sceneWorkshopsByParagraphUniqueCode/B048
Accept: application/json

###  获取全部现场车间
GET http://127.0.0.1:8000/api/wechatMiniApp/paragraphs
Accept: application/json

### 获取电务段代码
POST https://transmit.zhongchengkeshi.com/api/wechatMiniApp?timestamp=1&target=https://hefei.zhongchengkeshi.com/api/wechatMiniApp/correctMaintainLocation
#POST http://127.0.0.1:8000/api/wechatMiniApp/correctMaintainLocation
#POST http://changsha.zhongchengkeshi.com/api/wechatMiniApp/correctMaintainLocation
Content-Type: application/json

{
    "entire_instance_identity_code": "Q010101B04200000010",
    "maintain_station_name": "水家湖",
    "maintain_location_code": "01-01-02",
    "wechat_open_id": "AAA"
}

### 纠正上道位置
GET https://hefei.zhongchengkeshi.com/api/wechatMiniApp/stationInstallLocationCodesByWechatOpenId?wechat_open_id=AAA&timestamp=111
#GET https://transmit.zhongchengkeshi.com/api/wechatMiniApp?timestamp=111&wechat_open_id=AAA&target=https://hefei.zhongchengkeshi.com/api/wechatMiniApp/stationInstallLocationCodesByWechatOpenId
Accept: application/json

### 获取员工绑定记录
